You will use the values of what you find in this assignment to answer questions in the quiz that follows. You may want to open this notebook to be displayed side-by-side on screen with this next quiz.

1. Write a function that inputs an integers and returns the negative

In [3]:
# Write your function here
def neg(x):
    print('We print the negative value')
    y = x*-1
    return y

In [4]:
# Test your function with input x
x = 4
neg(x)

We print the negative value

-4

2. Write a function that inputs a list of integers and returns the minimum value

In [14]:
# Write your function here

def get_min(list):
    current_min = lst[0]
    for i in lst[1:]:
        if i < current_min:
            current_min = i
    return current_min

In [15]:
# Test your function with input lst
lst = [-3, 0, 2, 100, -1, 2]
get_min(lst)

# Create you own input list to test with

-3

#### Challenge problem:  
Write a function that take in four arguments: lst1, lst2, str1, str2, and returns a pandas DataFrame that has the first column labeled str1 and the second column labaled str2, that have values lst1 and lst2 scaled to be between 0 and 1.

For example
```
lst1 = [1, 2, 3]
lst2 = [2, 4, 5]
str1 = 'one'
str2 = 'two'

my_function(lst1, lst2, str1, str2)
``` 
should return a DataFrame that looks like:



|  <i></i> | one | two |
| --- | --- | --- |
| 0 | 0 | 0 |
| 1 | .5 | .666 |
| 2 | 1 | 1 |

In [24]:
def nopd(str1, str2, lst1, lst2):
    norm1 = [float(i)/sum(lst1) for i in lst1]
    norm2 = [float(i)/sum(lst2) for i in lst2]
    df = pd.DataFrame({str1:norm1, str2:norm2})
    return df

In [25]:
# test your challenge problem function
import pandas as pd
import numpy as np

lst1 = np.random.randint(-234, 938, 100)
lst2 = np.random.randint(-522, 123, 100)
str1 = 'one'
str2 = 'alpha'

nopd(str1, str2, lst1, lst2)

[ 926  514  369  207  492  856 -225 -145  215   36  439  -88  246  387
  -13  554  264  459  129  741  190  277  793  810 -234 -220  347  519
  363  171  264  107  390   -2  835  184   49  479    6  117  269  463
  445  175   88   46  712  632  383 -121  832   13  579  189  504  937
  334  784  572  822  591  180  360  403  302  522  887  -84  108   36
  380 -117 -205  833  882  108  391  497   51  132 -232 -227 -196  624
  780  -47   70 -206  314  -39 -169  621  809  514  503  867  -23  619
  433   -6]

         one     alpha
0   0.029182  0.017556
1   0.016198  0.013903
2   0.011629 -0.006140
3   0.006523  0.017556
4   0.015505  0.007865
5   0.026976  0.016998
6  -0.007091  0.013193
7  -0.004570  0.006799
8   0.006775 -0.001776
9   0.001135  0.021463
10  0.013835 -0.002588
11 -0.002773  0.019231
12  0.007752  0.026081
13  0.012196  0.024964
14 -0.000410  0.003146
15  0.017459  0.002436
16  0.008320  0.025167
17  0.014465  0.013446
18  0.004065  0.009945
19  0.023352  0.022478
20  0.005988 -0.005531
21  0.008729 -0.003501
22  0.024991  0.002283
23  0.025526  0.011315
24 -0.007374  0.020398
25 -0.006933 -0.005937
26  0.010935 -0.002791
27  0.016356  0.019231
28  0.011440  0.006546
29  0.005389  0.002486
..       ...       ...
70  0.011975  0.015324
71 -0.003687  0.026132
72 -0.006460  0.022884
73  0.026251  0.009083
74  0.027795  0.024609
75  0.003404  0.007662
76  0.012322  0.002841
77  0.015662  0.002841
78  0.001607  0.003806
79  0.004160 -0.005531
80 -0.007311  0.020956
81 -0.007154  0.020449
82 -0.006177  0.016998
83  0.019665  0.009945
84  0.024581  0.008524
85 -0.001481  0.018013
86  0.002206  0.012229
87 -0.006492  0.001015
88  0.009895  0.004364
89 -0.001229  0.007256
90 -0.005326  0.003603
91  0.019570 -0.003856
92  0.025495  0.020144
93  0.016198 -0.004364
94  0.015852  0.015780
95  0.027323 -0.002486
96 -0.000725  0.013599
97  0.019507 -0.002841
98  0.013646  0.021413
99 -0.000189  0.015527

[100 rows x 2 columns]